name: Publish to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install ".[docs]"; fi
          pip install jupyter-book
          pip install ghp-import
          pip list | grep -E 'jupyter|sphinx|ghp'
      - name: Build Jupyter Book Documentation
        run: |
          cd docs
          ln -sf ../notebooks .
          touch .nojekyll
          ls -la
          jupyter-book build . --verbose
          cp .nojekyll _build/html/
      - name: Deploy to GitHub Pages
        run: |
          cd docs
          ghp-import -n -p -f _build/html
