name: Publish to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install Dependencies
        run: |
          pip install -U pip
          # Install required Python built-in modules that might be missing in some Python builds
          python -c "import pip; pip.main(['install', 'setuptools'])" || true
          # Install compatible packages with correct versions
          pip install -U docutils==0.16 sphinx==3.5.4 jupyter-book==0.10.2 sphinx-book-theme==0.0.42
          # Additional dependencies
          pip install -U sphinx-multitoc-numbering==0.1.3 sphinx-panels sphinx-thebe
          pip install -U sphinx-external-toc==0.2.3
          # Skip the problematic pyproject.toml installation
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # if [ -f pyproject.toml ]; then pip install ".[docs]"; fi
      - name: Build Jupyter Book Documentation
        run: |
          touch docs/.nojekyll
          # Debug environment
          pip list | grep -E 'sphinx|docutils|myst|jupyter'
          # Install any missing modules
          pip list | grep -E 'imghdr' || pip install Pillow
          # Build without verbose to avoid token size issues
          jupyter-book build docs || jupyter-book build docs --config docs/_config.yml --toc docs/_toc.yml
          cp docs/.nojekyll docs/_build/html/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        with:
          path: "docs/_build/html"

  deploy-book:
    needs: build-book
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
